---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.1-bullseye

inputs:
  - name: dp-net
    path: dp-net

run:
  path: dp-net/ci/scripts/build.sh
